// import React from 'react'
import pic1 from "../../assets/images/art1.png";
import pic2 from "../../assets/images/art2.png";
import pic3 from "../../assets/images/art3.png";
import pic4 from "../../assets/images/art4.png";
import pic5 from "../../assets/images/art5.png";
import pic6 from "../../assets/images/art6.png";
import pic7 from "../../assets/images/art7.png";
const Art = () => {
  return (
    <div className="py-10  bg-black h-fit">
      <div className="typography font-zed flex flex-col items-center justify-center px-8">
        <h4 className="text-center text-slate-200 text-2xl md:text-3xl py-2 mb-2">
          {" "}
          Popular NFT’s generated by Artists
        </h4>
        <p className="text-gray-300  sm:text-lg w-10/12 text-center font-inter text-xl">
          {`3dotlink's AI integration is a game-changer in the NFT art world. It
          offers a powerful canvas for artists to redefine art creation and
          innovation while preserving cultural art in an entirely new format.
          With this platform, the convergence of human ingenuity and AI
          technology is set to redefine the boundaries of artistic expression
          and creative possibilities, ushering in a digital art renaissance.`}
        </p>
      </div>
      <div className="grid grid-cols-4 grid-row-3 gap-2 sm:gap-4  mt-8">
        <div className="overflow-hidden relative group  rounded-md">
          <img
            src={pic1}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover rounded-xl  "
            alt="pic1"
          />
          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>


          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>
        <div className="overflow-hidden relative group row-span-2 col-span-2">
          <img
            src={pic2}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover"
            alt="pic1"
          />

          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>

          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>
        <div className="overflow-hidden relative group">
          <img
            src={pic3}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover"
            alt="pic1"
          />

          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>

          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>
        <div className="overflow-hidden relative group row-span-2">
          <img
            src={pic5}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover"
            alt="pic1"
          />

          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>

          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>
        <div className="overflow-hidden relative group">
          <img
            src={pic4}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover"
            alt="pic1"
          />

          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>

          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>
        <div className="overflow-hidden relative group">
          <img
            src={pic6}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover rounded-xl"
            alt="pic1"
          />

          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>

          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>
        <div className="overflow-hidden relative group col-span-2 row-span-1">
          <img
            src={pic7}
            className="scale-100 group-hover:scale-110 transition-transform duration-500 ease-in-out w-full h-full object-cover"
            alt="pic1"
          />

          <div className="absolute inset-0 scale-0 w-2/3 h-2/3 m-auto  group-hover:scale-150 transition-transform duration-500 ease-in-out bg-red-500/20 border-2 border-red-800"></div>

          <div className="absolute inset-0 pointer-events-none group-hover:pointer-events-auto">
            <div className="absolute left-4 bottom-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out text-white">
              <h6 className="text-2xl font-medium font-zed">Bagwan</h6>
              <p className="font-inter text-xl">
                Art by <span className="text-primaryLight">xyz</span>
              </p>
            </div>
          </div>
        </div>


      </div>
    </div>
  );
};

export default Art;
